version: '1'

services:
  shortener:
    image: urlshortener/urlshortener
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"

    volumes:
      - ./db/urlshortner.db:/db/urlshortner.db