openapi: 3.0.0

info:
  title: URL Shortner OAS
  description: OpenApi specification for a url shortning service
  version: 1.0.0

servers:
  - url: http://localhost:3000/

components:
  schemas:
    urlRequest:
      type: object
      properties:
        user:
          type: string
          format: uuid
        url:
          type: string

      required:
        - user
        - url


    urlResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        user:
          type: string
          format: uuid
        url:
          type: string
        shortURL:
          type: string

        created_at:
          type: string
          format: date-time

      required:
        - id
        - user
        - url
        - shortURL
        - created_at

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

paths:
  /urls:
    post:
      description: Creates a new short url 
      operationId: shortenUrl
      requestBody:
        description: Shorten url
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/urlRequest'
      responses:
        '201': 
          description: Todo creation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urlResponse'
        default:
          description: unexpected error 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
