// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlite

import (
	"database/sql"
)

type Url struct {
	ID         int64
	Url        string
	Shorturl   string
	Userid     sql.NullInt64
	Createdate sql.NullInt64
}

type User struct {
	ID    int64
	Name  string
	Email string
}
