// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
  url, shorturl, userid, createdate
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, url, shorturl, userid, createdate
`

type CreateURLParams struct {
	Url        string
	Shorturl   string
	Userid     sql.NullInt64
	Createdate sql.NullInt64
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.Url,
		arg.Shorturl,
		arg.Userid,
		arg.Createdate,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Shorturl,
		&i.Userid,
		&i.Createdate,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email
) VALUES (
  ?, ?
)
RETURNING id, name, email
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM urls
WHERE id = ?
`

func (q *Queries) DeleteUrl(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUrl, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getLongURLFromShort = `-- name: GetLongURLFromShort :one
SELECT url FROM urls
WHERE shorturl = ? LIMIT 1
`

func (q *Queries) GetLongURLFromShort(ctx context.Context, shorturl string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLongURLFromShort, shorturl)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getShortURLFromLong = `-- name: GetShortURLFromLong :one
SELECT shorturl FROM urls
WHERE url = ? LIMIT 1
`

func (q *Queries) GetShortURLFromLong(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRowContext(ctx, getShortURLFromLong, url)
	var shorturl string
	err := row.Scan(&shorturl)
	return shorturl, err
}

const getURL = `-- name: GetURL :one
SELECT id, url, shorturl, userid, createdate FROM urls
WHERE url = ? LIMIT 1
`

func (q *Queries) GetURL(ctx context.Context, url string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURL, url)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Shorturl,
		&i.Userid,
		&i.Createdate,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const listURLs = `-- name: ListURLs :many
SELECT id, url, shorturl, userid, createdate FROM urls
ORDER BY url
`

func (q *Queries) ListURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Shorturl,
			&i.Userid,
			&i.Createdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
