// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// UrlRequest defines model for urlRequest.
type UrlRequest struct {
	Url  string             `json:"url"`
	User openapi_types.UUID `json:"user"`
}

// UrlResponse defines model for urlResponse.
type UrlResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        int32              `json:"id"`
	ShortURL  string             `json:"shortURL"`
	Url       string             `json:"url"`
	User      openapi_types.UUID `json:"user"`
}

// ShortenUrlJSONRequestBody defines body for ShortenUrl for application/json ContentType.
type ShortenUrlJSONRequestBody = UrlRequest
