openapi: 3.0.0

info:
  title: URL Shortener OAS
  description: OpenApi specification for a url shortening service
  version: 1.0.0

servers:
  - url: http://localhost:3000/

components:
  schemas:
    ShortenURLRequest:
      type: object
      properties:
        url:
          type: string
      required:
        - url

    ShortenURLResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          type: integer
          format: int64
        url:
          type: string
        shortURL:
          type: string
        created_at:
          type: integer
          format: int64

      required:
        - id
        - user
        - url
        - shortURL
        - created_at

    ShortUrlRequest:
      type: object
      properties:
        url:
          type: string
      required:
        - url

    ShortUrlResponse:
      type: object
      properties:
        url:
          type: string
      required:
        - url

    SignUpRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    SignUpResponse:
      type: object
      properties:
        apikey:
          type: string

    SignInRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    SignInResponse:
      type: object
      properties:
        apikey:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key

paths:
  /urls:
    x-go-middlewares: [validateAPIKey]
    post:
      description: Creates a new short url
      operationId: shortenUrl
      security:
        - ApiKeyAuth: []
      requestBody:
        description: Shorten url
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShortenURLRequest"
      responses:
        "201":
          description: Shortened url creation response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortenURLResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /urls/{URL}:
    x-go-middlewares: [validateAPIKey]
    get:
      description: Gets a shortened url
      operationId: getLongURLFromShort
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: URL
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Shortened Url Exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortUrlResponse"
        "404":
          description: Url doesn's exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/signup:
    post:
      description: Sign up new user
      operationId: postSignUp
      requestBody:
        description: signup user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        "201":
          description: user api key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUpResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/signin:
    post:
      description: Sign in a user
      operationId: postSignIn
      requestBody:
        description: signin
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
      responses:
        "201":
          description: user api key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
